"""Add amount field to CommissionInvoice

Revision ID: 3947efd62aa2
Revises: 3bdbeb0cd8fa
Create Date: 2025-07-12 16:36:46.073656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3947efd62aa2'
down_revision = '3bdbeb0cd8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_invoice', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
