"""update commission_invoices structure

Revision ID: 3bdbeb0cd8fa
Revises: 4c22cac77de3
Create Date: 2025-07-12 14:12:26.934805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdbeb0cd8fa'
down_revision = '4c22cac77de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commission_invoices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=30), nullable=False),
    sa.Column('voucher_id', sa.INTEGER(), nullable=False),
    sa.Column('factory_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('pdf_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    # ### end Alembic commands ###
